package Just_in_Case.backend;

public enum Location {
    ADELBERT_HALL, 
    ADELBERT_GYM, 
    WOLSTEIN_HALL, 
    AMASA_STONE_CHAPEL,
    ART_STUDIO, 
    BOOKSTORE, 
    BELLFLOWER_HALL, 
    BINGHAM, 
    CARLTON_COMMONS, 
    CLARK_HALL, 
    //CLEVELAND_CENTER_FOR_MOLECULAR_AND_STRUCTURAL_BIOLOGY
    CLEVELAND_HILLEL_FOUNDATION,
    CRAWFORD_HALL, //College of arts and sciences
    CUTTER,
    DISANTO_FIELD,
    DIVELY,
    ELDRED,
    EMERSON_GYM,
    FRIBLEY_COMMONS,
    GLENNAN,
    GUEST_HOUSE, //?
    GUILFORD,
    HARCOURT_HOUSE,
    HARKNESS_CHAPEL,
    HAYDN,
    HEALTH_SERVICE,
    HEALTH_EDUCATION_CAMPUS,
    HORSBURGH_GYM,
    KELVIN_SMITH_LIBRARY, //UTech C.A.R.E. Center
    LEUTNER_COMMONS,
    LINSALATA_ALUMNI_CENTER,
    JACK_JOSEPH_AND_MORTON_MANDEL_COMM_STUDIES, //?
    MATHER_DANCE_CENTER,
    MATHER_HOUSE,
    MATHER_MEMORIAL,
    MATHER_PARK,
    MORLEY,
    MALTZ, //THE MILTON AND TAMAR MALTZ MERFORMING ARTS CENTER AT THE TEMPLE-TIFERETH ISRAEL
    MT_SINAI_SKLLS_AND_SIMULATION_CENTER, //?
    NOBBYS_BALLPARK,
    NORD,
    OLIN,
    ONE_TO_ONE_FITNESS,
    PUBLIC_SAFETY_AND_SECURITY,
    PYTTE_SCIENCE_CENTER,
    MILLIS_SCHMITT,
    CLAPP,
    DEGRACE_CENTER,
    SEARS_THINKBOX,
    ROCKEFELLER,
    ROBBINS,
    SEARS,
    SEARS_TOWER,
    SECURITY_NORTH_CAMPUS, //?
    SERVICE_BUILDING, //?
    AW_SMITH,
    KENT_HALE_SMITH,
    SOUTH_RESIDENTIAL_VILLAGE,
    STEINER,
    STONE,
    STROSACKER,
    THWING_CENTER,
    TINKHAM_VEALE_UNIVERSITY_CENTER,
    TOBYS_PLAZA,
    TOMLINSON_HALL,
    VAN_HORN_FIELD,
    VEALE_CENTER,
    WADE_COMMONS,
    WHITE,
    WICKENDEN,
    WOLSTEIN_RESEARCH,
    WOOD,
    WYANT_ATHLETIC_AND_WELLNESS_CENTER,
    YOST,

    //UNIVERSITY HOUSING
    //NRV
    CLARKE_TOWER,
    CUTLER,
    HITCHCOCK,
    NORTON,
    THE_VILLAGE_AT_115,
    PIERCE,
    RAYMOND,
    SHERMAN,
    SMITH,
    STEPHANIE_TUBBS_JONES,
    STORRS,
    TAFT,
    TAPLIN,
    TYLER,
    //GREEK
    ALPHA_CHI_OMEGA,
    ALPHA_PHI,
    DELTA_TAU_DELTA,
    PHI_GAMMA_DELTA,
    PHI_KAPPA_THETA,
    PHI_MU,
    THETA_CHI,
    ZETA_BETA_TAU,
    //SRV
    ALUMNI,
    GLASER,
    HOWE,
    KUSCH,
    MICHELSON,
    STALEY,
    TIPPIT,
    //GREEK
    BETA_THETA_PI,
    DELTA_GAMMA,
    DELTA_UPSILON,
    KAPPA_ALPHA_THETA,
    PHI_DELTA_THETA,
    PHI_KAPPA_PSI,
    PHI_SIGMA_RHO,
    PI_BETA_PHI,
    SIGMA_CHI,
    SIGMA_NU,
    SIGMA_PSI,
    ZETA_PSI,
    //APTMTS
    BUILDING1680,
    BUILDING1719,
    BUILDING1727,
    THE_NOBLE,
    TRIANGLE,
    TWIN_GABLES,

    //UNIVERSITY CIRCLE
    EUCLID_ADELBERT,
    CHURCH_OF_THE_COVENANT,
    CLEVELAND_BOTANICAL_GARDEN,
    CLEVELAND_CLINIC,
    CLEVELAND_HEARING_AND_SPEECH_CENTER,
    CLEVELAND_INSTITUTE_OF_ART,
    CLEVELAND_INSTITUTE_OF_MUSIC,
    CLEVELAND_MUSEUM_OF_ART,
    CLEVELAND_MUSEUM_OF_NATURAL_HISTORY,
    COFFEE_HOUSE_AT_UNIVERSITY_CIRCLE,
    GLIDDEN_HOUSE,
    LALBATROS,
    MUSEUM_OF_CONTEMPORARY_ART,
    RTA_CEDAR_UNIVERSITY,
    RTA_LITTLE_ITALY,
    SEVERANCE_HALL,
    STARBUCKS_NRV,
    THE_DEN_BY_DENNYS,
    UNIVERSITY_HOSPITALS;

    //should we add the different UH buildings?








    





    /* 
    don't know if i should include:
    gund hall school of law
    jack, joseph and morton mandel school of applied social sciences
    school of dental medicine clinic
    weatherhead school of management (peter b lewis)
    SCHOOL OF GRADUATE STUDIES- TOMLINSON
    ALLEN MEMORAL MEDICAL LIBRARY
    BIOENTERPRISE
    BIOMEDICAL RESEARCH
    CEDAR AVENUE SERVICE CENTER



    other notes:
    wolstein hall is admission office (undergraduate)

    link where i got this: https://case.edu/pdc/sites/case.edu.pdc/files/2018-11/campus-map-1018.pdf
    */
}
